services:

  db:
    image: mariadb:12.0
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      backend:

  app:
    image: egoexpress/gitea:1.24
    volumes:
      - data:/data
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - SSL_POLICY=Mozilla-Modern
    depends_on:
      - db
    restart: always
    networks:
      frontend:
      backend:

networks:
  frontend:
    name: proxy_frontend
    external: true
  backend:
    internal: true

volumes:
  db:
  data:
