version: '3'

services:

  db:
    image: mariadb:11.2
    restart: always
    volumes:
      - db:/var/lib/mysql
    networks:
      backend:

  app:
    image: egoexpress/gitea:1.21
    volumes:
      - data:/data
    depends_on:
      - db
    restart: always
    networks:
      frontend:
      backend:

networks:
  frontend:
  backend:
    internal: true

volumes:
  db:
  data:
