version: '3'

services:

  db:
    image: mariadb:10.6
    restart: always
    volumes:
      - db/:/var/lib/mysql
    networks:
      backend:

  app:
    image: gitea/gitea:1.15
    volumes:
      - data:/data
    depends_on:
      - db
    restart: always
    networks:
      frontend:
      backend:

networks:
  frontend:
    external:
      name: proxy_frontend
  backend:

volumes:
  db:
  data:
